version: "3"
volumes:
  postgres-data:
    driver: local
  postgres-testdata:
    driver: local
services:
  backend:
    restart: always
    build: ./back-end
    ports:
      - "8000:8000"
    links:
      - postgresdb:postgresdb
    volumes:
      - ./back-end/:/usr/src/app
    env_file: .env
  frontend:
    build: ./front-end
    ports:
      - "8082:8082"
    env_file: .env
    command: npm run dev
    volumes:
      - ./front-end/:/usr/src/app
      - /usr/src/app/node_modules
  postgresdb:
    restart: always
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres

    
  