"""empty message

Revision ID: 3e336daeb5b6
Revises: 37999ee67021
Create Date: 2017-05-30 18:08:10.176767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e336daeb5b6'
down_revision = '37999ee67021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('todo_name', sa.String(length=300), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('todo_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
