"""empty message

Revision ID: 4753a6561838
Revises: 
Create Date: 2017-06-03 11:41:47.644959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4753a6561838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('todo_name', sa.String(length=300), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('todo_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
